# Generated by Django 6.0.1 on 2026-01-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobrun",
            name="engine",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="jobrun",
            name="execution_time_ms",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobrun",
            name="processed_items",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
