# Generated by Django 6.0.1 on 2026-01-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_jobrun_engine_alter_jobrun_execution_time_ms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrun",
            name="average_age",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
