# Generated by Django 5.2.10 on 2026-01-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobrun_average_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrun',
            name='execution_time_ms',
        ),
        migrations.AddField(
            model_name='jobrun',
            name='cpu_time_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='memory_mb_peak',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
